<?php

use Illuminate\Database\Seeder;
use App\Enums\AmmoType;
use App\Enums\ArmorMaterial;
use App\Enums\AttackType;
use App\Enums\ItemType;
use App\Utils\IntegerUtil;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $items = [
            [
                'type' => ItemType::Weapon,
                'name' => 'bear_hands',
                'attack_type' => IntegerUtil::defactorize([AttackType::Fist]),
                'point' => 0,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'crossbow',
                'attack_type' => IntegerUtil::defactorize([AttackType::Bow, AttackType::Melee]),
                'point' => 20,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 1,
                'ammo_type' => AmmoType::Arrow,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'kitchen_knife',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 15,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'hand_axe',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut]),
                'point' => 17,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'remington_mk31',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 28,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 5,
                'ammo_type' => AmmoType::ShotGun12Gauge,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'knife',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 17,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],   
            [
                'type' => ItemType::Weapon,
                'name' => 'dagger',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 15,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'mac_10',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 30,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 32,
                'ammo_type' => AmmoType::Pistol9MM,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'fork',
                'attack_type' => IntegerUtil::defactorize([AttackType::Stab]),
                'point' => 7,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'metal_bet',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 15,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'derringer',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 20,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 2,
                'ammo_type' => AmmoType::Rifle22LR,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'military_knife',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab, AttackType::Throw]),
                'point' => 20,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'walther_ppk',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 25,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 8,
                'ammo_type' => AmmoType::Pistol9MM,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'm19_magnum',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 26,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 6,
                'ammo_type' => AmmoType::Magnum357,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'beretta_m9',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 25,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 14,
                'ammo_type' => AmmoType::Pistol9MM,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'm36_revolver',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 23,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 5,
                'ammo_type' => AmmoType::Revolver38Special,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'python_magnum',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 27,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 6,
                'ammo_type' => AmmoType::Magnum357,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'dagger_knife',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 20,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],   
            [
                'type' => ItemType::Weapon,
                'name' => 'browning_hipower',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 26,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 14,
                'ammo_type' => AmmoType::Pistol9MM,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'divers_knife',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 20,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],     
            [
                'type' => ItemType::Weapon,
                'name' => 'dart',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 5,
                'endurance' => 12,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'grenade',
                'attack_type' => IntegerUtil::defactorize([AttackType::Bomb]),
                'point' => 40,
                'endurance' => 2,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],   
            [
                'type' => ItemType::Weapon,
                'name' => 'm59_pistol',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 24,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 15,
                'ammo_type' => AmmoType::Pistol9MM,
                'armor_material' => ArmorMaterial::None
            ],   
            [
                'type' => ItemType::Weapon,
                'name' => 'baton',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 13,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'm28_38special',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 24,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 6,
                'ammo_type' => AmmoType::Revolver38Special,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'sickle',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 20,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],      
            [
                'type' => ItemType::Weapon,
                'name' => 'ice_pick',
                'attack_type' => IntegerUtil::defactorize([AttackType::Stab]),
                'point' => 8,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],  
            [
                'type' => ItemType::Weapon,
                'name' => 'nunchaku',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 12,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],   
            [
                'type' => ItemType::Weapon,
                'name' => 'boomerang',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 9,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],       
            [
                'type' => ItemType::Weapon,
                'name' => 'cz_m75',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 25,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 16,
                'ammo_type' => AmmoType::Pistol9MM,
                'armor_material' => ArmorMaterial::None
            ],   
            [
                'type' => ItemType::Weapon,
                'name' => 'uzi_9mm',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 30,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 32,
                'ammo_type' => AmmoType::Pistol9MM,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'p230_9mm',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 26,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 8,
                'ammo_type' => AmmoType::Pistol9MM,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'm1911_45acp',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 25,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 8,
                'ammo_type' => AmmoType::Pistol45ACP,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'katana',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 25,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],     
            [
                'type' => ItemType::Weapon,
                'name' => 'hand_fan',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 1,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],      
            [
                'type' => ItemType::Weapon,
                'name' => 'rubber_basin',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 3,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],      
            [
                'type' => ItemType::Weapon,
                'name' => 'slipper',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 2,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],      
            [
                'type' => ItemType::Weapon,
                'name' => 'blackboard_eraser',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 2,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],       
            [
                'type' => ItemType::Weapon,
                'name' => 'chalk',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],       
            [
                'type' => ItemType::Weapon,
                'name' => 'baseball_bat',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 12,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],      
            [
                'type' => ItemType::Weapon,
                'name' => 'knuckle',
                'attack_type' => IntegerUtil::defactorize([AttackType::Fist]),
                'point' => 8,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'toy_hammer',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 1,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],      
            [
                'type' => ItemType::Weapon,
                'name' => 'molotov_cocktail',
                'attack_type' => IntegerUtil::defactorize([AttackType::Bomb]),
                'point' => 15,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],   
            [
                'type' => ItemType::Weapon,
                'name' => 'bomb',
                'attack_type' => IntegerUtil::defactorize([AttackType::Bomb]),
                'point' => 60,
                'endurance' => 3,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],   
            [
                'type' => ItemType::Weapon,
                'name' => 'temp_flamethrower',
                'attack_type' => IntegerUtil::defactorize([AttackType::Bomb]),
                'point' => 10,
                'endurance' => 8,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],   
            [
                'type' => ItemType::Weapon,
                'name' => 'chain_sickle',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Melee]),
                'point' => 22,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],      
            [
                'type' => ItemType::Weapon,
                'name' => 'nailed_bat',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 20,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],      
            [
                'type' => ItemType::Weapon,
                'name' => 'nailed_bamboo',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 13,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],      
            [
                'type' => ItemType::Weapon,
                'name' => 'stone_axe',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 15,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'custom_knife',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 20,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],     
            [
                'type' => ItemType::Weapon,
                'name' => 'catapult',
                'attack_type' => IntegerUtil::defactorize([AttackType::Bow, AttackType::Melee]),
                'point' => 25,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 1,
                'ammo_type' => AmmoType::Arrow,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'bamboo_spear',
                'attack_type' => IntegerUtil::defactorize([AttackType::Stab]),
                'point' => 20,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'crescent_blade',
                'attack_type' => IntegerUtil::defactorize([AttackType::Stab]),
                'point' => 40,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'double_knife',
                'attack_type' => IntegerUtil::defactorize([AttackType::Stab]),
                'point' => 35,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'dynamite',
                'attack_type' => IntegerUtil::defactorize([AttackType::Bomb]),
                'point' => 30,
                'endurance' => 8,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],   
            [
                'type' => ItemType::Weapon,
                'name' => 'stones',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 15,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'cup',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 10,
                'endurance' => 4,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'baseball_balls',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 20,
                'endurance' => 30,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'glass_plate',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 10,
                'endurance' => 4,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'television',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 20,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'dining_table',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 20,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'shelf',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 15,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'precious_sword',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 20,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'empty_bottle',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 1,
                'endurance' => 10,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'empty_can',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 2,
                'endurance' => 10,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'glass_goblet',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 10,
                'endurance' => 4,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'pot',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 10,
                'endurance' => 4,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'chains',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 15,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'frying_pan',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 15,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'fire_axe',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut]),
                'point' => 20,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'fire_extinguisher',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 12,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'quan_yin_bodhisattva_statue',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 5,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'yama_raja_statue',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 7,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'asura_statue',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 10,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'ksitigarbha_statue',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 8,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'bow',
                'attack_type' => IntegerUtil::defactorize([AttackType::Bow, AttackType::Melee]),
                'point' => 20,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 1,
                'ammo_type' => AmmoType::Arrow,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'pickaxe',
                'attack_type' => IntegerUtil::defactorize([AttackType::Stab]),
                'point' => 15,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '스카프',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 10,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'sabre',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 5,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'rocks',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 20,
                'endurance' => 8,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'wooden_fish',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '솔도파',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 4,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'pencil',
                'attack_type' => IntegerUtil::defactorize([AttackType::Stab]),
                'point' => 2,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'eraser',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'glass_flask',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'mop',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 8,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'white_chalk',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 2,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'red_chalk',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 2,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'yellow_chalk',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 2,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'blue_chalk',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 2,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'human_body_model',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 3,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'giant_set_square',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 4,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'giant_compasses',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 8,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'chair',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 4,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'bamboo',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 6,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'wooden_sword',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 12,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'firelock',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 20,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 1,
                'ammo_type' => AmmoType::MusketBall,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'masamune_great_sword',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 23,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'japanese_bow',
                'attack_type' => IntegerUtil::defactorize([AttackType::Bow, AttackType::Melee]),
                'point' => 18,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 1,
                'ammo_type' => AmmoType::Arrow,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'soldering_iron',
                'attack_type' => IntegerUtil::defactorize([AttackType::Stab]),
                'point' => 6,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'broken_laptop',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 10,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'shuriken',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 30,
                'endurance' => 15,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'heavy_crossbow',
                'attack_type' => IntegerUtil::defactorize([AttackType::Bow, AttackType::Melee]),
                'point' => 30,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 1,
                'ammo_type' => AmmoType::Arrow,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'razor',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut]),
                'point' => 5,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'butterfly_knife',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 8,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'hanafuda',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'playing_cards',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'portable_console',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 2,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'soap',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 1,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'toothbrush',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 1,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'masamune_magical_sword',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 25,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'muramasa_magical_sword',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 23,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'm16a2',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 30,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 30,
                'ammo_type' => AmmoType::Rifle556MM,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => 'underwear',
                'attack_type' => AttackType::None,
                'point' => 0,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Fabric
            ],
            [
                'type' => ItemType::ArmorHead,
                'name' => 'necklace',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorHead,
                'name' => 'hairpin',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 2,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorHead,
                'name' => 'glasses',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorAccessory,
                'name' => 'magazine',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 2,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorAccessory,
                'name' => 'tamagotchi',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 3,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorAccessory,
                'name' => 'cd_player',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 3,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorAccessory,
                'name' => 'bulletproof_vest',
                'attack_type' => AttackType::None,
                'point' => 5,
                'endurance' => 10,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorLeg,
                'name' => 'hiking_boots',
                'attack_type' => AttackType::None,
                'point' => 3,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorHead,
                'name' => 'hiking_helmet',
                'attack_type' => AttackType::None,
                'point' => 2,
                'endurance' => 3,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorArm,
                'name' => 'bracelet',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 2,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorArm,
                'name' => 'fur_cuffs',
                'attack_type' => AttackType::None,
                'point' => 2,
                'endurance' => 3,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorArm,
                'name' => 'civil_defense_armbands',
                'attack_type' => AttackType::None,
                'point' => 2,
                'endurance' => 3,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorArm,
                'name' => 'rural_armbands',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 2,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorHead,
                'name' => 'hairband',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 3,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => 'fire_suit',
                'attack_type' => AttackType::None,
                'point' => 10,
                'endurance' => 20,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Fabric
            ],
            [
                'type' => ItemType::ArmorHead,
                'name' => 'fire_helmet',
                'attack_type' => AttackType::None,
                'point' => 3,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => 'monk_cloth',
                'attack_type' => AttackType::None,
                'point' => 8,
                'endurance' => 20,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Fabric
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => 'shamen_cloth',
                'attack_type' => AttackType::None,
                'point' => 8,
                'endurance' => 15,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Fabric
            ],
            [
                'type' => ItemType::ArmorLeg,
                'name' => 'clog',
                'attack_type' => AttackType::None,
                'point' => 2,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorHead,
                'name' => 'safety_helmet',
                'attack_type' => AttackType::None,
                'point' => 4,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => 'boilersuit',
                'attack_type' => AttackType::None,
                'point' => 8,
                'endurance' => 10,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Fabric
            ],
            [
                'type' => ItemType::ArmorHead,
                'name' => 'motorcycle_helmet',
                'attack_type' => AttackType::None,
                'point' => 4,
                'endurance' => 10,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorHead,
                'name' => 'ribbon',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 2,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorLeg,
                'name' => 'running_shoes',
                'attack_type' => AttackType::None,
                'point' => 3,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorArm,
                'name' => 'duty_student_armband',
                'attack_type' => AttackType::None,
                'point' => 3,
                'endurance' => 3,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorArm,
                'name' => 'cuffs',
                'attack_type' => AttackType::None,
                'point' => 2,
                'endurance' => 20,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorLeg,
                'name' => 'indoor_shoes',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 2,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorHead,
                'name' => 'rusty_helmet',
                'attack_type' => AttackType::None,
                'point' => 4,
                'endurance' => 3,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => 'white_clothes',
                'attack_type' => AttackType::None,
                'point' => 10,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Fabric
            ],
            [
                'type' => ItemType::ArmorLeg,
                'name' => 'rainboots',
                'attack_type' => AttackType::None,
                'point' => 4,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => 'armor',
                'attack_type' => AttackType::None,
                'point' => 12,
                'endurance' => 20,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Armor
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => 'chainmail_armor',
                'attack_type' => AttackType::None,
                'point' => 12,
                'endurance' => 20,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Chain
            ],
            [
                'type' => ItemType::ArmorHead,
                'name' => 'combat_helmet',
                'attack_type' => AttackType::None,
                'point' => 5,
                'endurance' => 10,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => 'precious_armor',
                'attack_type' => AttackType::None,
                'point' => 14,
                'endurance' => 20,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Armor
            ],
            [
                'type' => ItemType::ArmorLeg,
                'name' => 'rubber_shoes',
                'attack_type' => AttackType::None,
                'point' => 2,
                'endurance' => 4,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorLeg,
                'name' => 'high_heel',
                'attack_type' => AttackType::None,
                'point' => 3,
                'endurance' => 3,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorLeg,
                'name' => 'military_boots',
                'attack_type' => AttackType::None,
                'point' => 5,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorHead,
                'name' => 'military_helmet',
                'attack_type' => AttackType::None,
                'point' => 5,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorArm,
                'name' => 'drill_surgent_armband',
                'attack_type' => AttackType::None,
                'point' => 5,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorArm,
                'name' => 'mp_armband',
                'attack_type' => AttackType::None,
                'point' => 4,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => 'military_uniform',
                'attack_type' => AttackType::None,
                'point' => 12,
                'endurance' => 40,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Fabric
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => 'school_uniform',
                'attack_type' => AttackType::None,
                'point' => 5,
                'endurance' => 30,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Fabric
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => 'women_school_uniform',
                'attack_type' => AttackType::None,
                'point' => 5,
                'endurance' => 30,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Fabric
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => 'gym_suit',
                'attack_type' => AttackType::None,
                'point' => 5,
                'endurance' => 30,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Fabric
            ],
            [
                'type' => ItemType::ArmorLeg,
                'name' => 'slipper',
                'attack_type' => AttackType::None,
                'point' => 3,
                'endurance' => 10,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => 'mild_seven_cigarettes',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => 'chocolate',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => 'cookie',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => 'sweet_potato',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => 'yam',
                'attack_type' => AttackType::None,
                'point' => 20,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => 'potato',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => 'burdock',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => 'carrot',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => 'onion',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => 'garlic',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => 'ginger',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => 'curry_powder',
                'attack_type' => AttackType::None,
                'point' => 20,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => 'soy_source',
                'attack_type' => AttackType::None,
                'point' => 20,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => 'source',
                'attack_type' => AttackType::None,
                'point' => 20,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => 'energy_drink',
                'attack_type' => AttackType::None,
                'point' => 100,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => 'stew',
                'attack_type' => AttackType::None,
                'point' => 50,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => 'bread',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 2,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => 'hardtack',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 2,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionHealth,
                'name' => 'whiskey',
                'attack_type' => AttackType::None,
                'point' => 20,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionHealth,
                'name' => 'water',
                'attack_type' => AttackType::None,
                'point' => 20,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionHealth,
                'name' => 'pill',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionHealth,
                'name' => 'powder_juice',
                'attack_type' => AttackType::None,
                'point' => 30,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionHealth,
                'name' => 'first_aid',
                'attack_type' => AttackType::None,
                'point' => 50,
                'endurance' => 3,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Trap,
                'name' => 'mousetrap',
                'attack_type' => AttackType::None,
                'point' => 10,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Trap,
                'name' => 'mine',
                'attack_type' => AttackType::None,
                'point' => 8,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Trap,
                'name' => 'piano_wire',
                'attack_type' => AttackType::None,
                'point' => 8,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Trap,
                'name' => 'enchanted_mine',
                'attack_type' => AttackType::None,
                'point' => 20,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Phone,
                'name' => 'phone',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => 'primer',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => 'fireworks',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => 'hair_spray',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => 'lighter',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::TempRadar,
                'name' => 'temp_radar',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => 'shamisen_wire',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Poison,
                'name' => 'poison',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Ammo,
                'name' => '12gauge_shell',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 24,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::ShotGun12Gauge,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Ammo,
                'name' => '9mm_ammo',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 24,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::Pistol9MM,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Ammo,
                'name' => '22lr_ammo',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 24,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::Rifle22LR,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Ammo,
                'name' => '357mag_ammo',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 24,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::Magnum357,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Ammo,
                'name' => 'musket_ball',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 24,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::MusketBall,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Ammo,
                'name' => '38sp_ammo',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 24,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::Revolver38Special,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Ammo,
                'name' => '45acp_ammo',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 24,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::Pistol45ACP,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Ammo,
                'name' => 'arrow',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 12,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::Arrow,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorRefine,
                'name' => 'sewing_tools',
                'attack_type' => AttackType::None,
                'point' => 3,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::WeaponRefine,
                'name' => 'whetstone',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => 'gasoline',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => 'disel',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => 'fertilizer',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Speaker,
                'name' => 'loud_speaker',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => 'battery',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => 'nail',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => 'fuze',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Radar,
                'name' => 'radar',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => 'gunpowder',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => 'laptop',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::MobilePc,
                'name' => 'portable_pc',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => 'shaft',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Program,
                'name' => 'program_key',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
        ];

        foreach ($items as $item) {
            DB::table('items')->insert($item);
        }
    }
}
