<?php

use Illuminate\Database\Seeder;
use App\Enums\AmmoType;
use App\Enums\ArmorMaterial;
use App\Enums\AttackType;
use App\Enums\ItemType;
use App\Utils\IntegerUtil;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $items = [
            [
                'type' => ItemType::Weapon,
                'name' => '맨손',
                'attack_type' => IntegerUtil::defactorize([AttackType::Fist]),
                'point' => 0,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '석궁',
                'attack_type' => IntegerUtil::defactorize([AttackType::Bow, AttackType::Melee]),
                'point' => 20,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 1,
                'ammo_type' => AmmoType::Arrow,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '식칼',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 15,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '손도끼',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut]),
                'point' => 17,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '레밍턴M31RS',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 28,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 5,
                'ammo_type' => AmmoType::ShotGun12Gauge,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '나이프',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 17,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],   
            [
                'type' => ItemType::Weapon,
                'name' => '단도',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 15,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '잉그램M10 서브머신건',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 30,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 32,
                'ammo_type' => AmmoType::Pistol9MM,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '포크',
                'attack_type' => IntegerUtil::defactorize([AttackType::Stab]),
                'point' => 7,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '금속 배트',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 15,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '22구경 2연발 데린져',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 20,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 2,
                'ammo_type' => AmmoType::Rifle22LR,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '군용 나이프',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab, AttackType::Throw]),
                'point' => 20,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '월터PPK 9밀리',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 25,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 8,
                'ammo_type' => AmmoType::Pistol9MM,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'S&W M19 357 매그넘',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 26,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 6,
                'ammo_type' => AmmoType::Magnum357,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '베레타M92F',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 25,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 14,
                'ammo_type' => AmmoType::Pistol9MM,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'S&W 치프스페셜 38구경',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 23,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 5,
                'ammo_type' => AmmoType::Revolver38Special,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '콜트357 매그넘 리볼버',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 27,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 6,
                'ammo_type' => AmmoType::Magnum357,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '양날 나이프',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 20,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],   
            [
                'type' => ItemType::Weapon,
                'name' => '브라우닝 하이파워 9mm',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 26,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 14,
                'ammo_type' => AmmoType::Pistol9MM,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '다이버즈 나이프',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 20,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],     
            [
                'type' => ItemType::Weapon,
                'name' => '다트',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 5,
                'endurance' => 12,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '수류탄',
                'attack_type' => IntegerUtil::defactorize([AttackType::Bomb]),
                'point' => 40,
                'endurance' => 2,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],   
            [
                'type' => ItemType::Weapon,
                'name' => 'S&W M59 오토',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 24,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 15,
                'ammo_type' => AmmoType::Pistol9MM,
                'armor_material' => ArmorMaterial::None
            ],   
            [
                'type' => ItemType::Weapon,
                'name' => '특수경봉',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 13,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '콜트 하이웨이 패트롤맨 38구경',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 24,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 6,
                'ammo_type' => AmmoType::Revolver38Special,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '낫',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 20,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],      
            [
                'type' => ItemType::Weapon,
                'name' => '얼음송곳',
                'attack_type' => IntegerUtil::defactorize([AttackType::Stab]),
                'point' => 8,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],  
            [
                'type' => ItemType::Weapon,
                'name' => '눈쳐크',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 12,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],   
            [
                'type' => ItemType::Weapon,
                'name' => '부메랑',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 9,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],       
            [
                'type' => ItemType::Weapon,
                'name' => 'CZ M75',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 25,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 16,
                'ammo_type' => AmmoType::Pistol9MM,
                'armor_material' => ArmorMaterial::None
            ],   
            [
                'type' => ItemType::Weapon,
                'name' => '우지 9mm 서브머신건',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 30,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 32,
                'ammo_type' => AmmoType::Pistol9MM,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '시그 사우엘 P230 9mm',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 26,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 8,
                'ammo_type' => AmmoType::Pistol9MM,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '콜트 거버먼트 45구경',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 25,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 8,
                'ammo_type' => AmmoType::Pistol45ACP,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '일본도',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 25,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],     
            [
                'type' => ItemType::Weapon,
                'name' => '부채',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 1,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],      
            [
                'type' => ItemType::Weapon,
                'name' => '대야',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 3,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],      
            [
                'type' => ItemType::Weapon,
                'name' => '슬리퍼',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 2,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],      
            [
                'type' => ItemType::Weapon,
                'name' => '칠판지우개',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 2,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],       
            [
                'type' => ItemType::Weapon,
                'name' => '분필',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],       
            [
                'type' => ItemType::Weapon,
                'name' => '배트',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 12,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],      
            [
                'type' => ItemType::Weapon,
                'name' => '너클',
                'attack_type' => IntegerUtil::defactorize([AttackType::Fist]),
                'point' => 8,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '뿅망치',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 1,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],      
            [
                'type' => ItemType::Weapon,
                'name' => '화염병',
                'attack_type' => IntegerUtil::defactorize([AttackType::Bomb]),
                'point' => 15,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],   
            [
                'type' => ItemType::Weapon,
                'name' => '폭탄',
                'attack_type' => IntegerUtil::defactorize([AttackType::Bomb]),
                'point' => 60,
                'endurance' => 3,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],   
            [
                'type' => ItemType::Weapon,
                'name' => '간이화염방사기',
                'attack_type' => IntegerUtil::defactorize([AttackType::Bomb]),
                'point' => 10,
                'endurance' => 8,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],   
            [
                'type' => ItemType::Weapon,
                'name' => '사슬낫',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Melee]),
                'point' => 22,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],      
            [
                'type' => ItemType::Weapon,
                'name' => '못박은배트',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 20,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],      
            [
                'type' => ItemType::Weapon,
                'name' => '못박은대나무',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 13,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],      
            [
                'type' => ItemType::Weapon,
                'name' => '돌도끼',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 15,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '커스텀나이프',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 20,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],     
            [
                'type' => ItemType::Weapon,
                'name' => '쇠뇌',
                'attack_type' => IntegerUtil::defactorize([AttackType::Bow, AttackType::Melee]),
                'point' => 25,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 1,
                'ammo_type' => AmmoType::Arrow,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '죽창',
                'attack_type' => IntegerUtil::defactorize([AttackType::Stab]),
                'point' => 20,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '언월도',
                'attack_type' => IntegerUtil::defactorize([AttackType::Stab]),
                'point' => 40,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '쌍칼',
                'attack_type' => IntegerUtil::defactorize([AttackType::Stab]),
                'point' => 35,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '다이나마이트',
                'attack_type' => IntegerUtil::defactorize([AttackType::Bomb]),
                'point' => 30,
                'endurance' => 8,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],   
            [
                'type' => ItemType::Weapon,
                'name' => '돌맹이',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 15,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '컵',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 10,
                'endurance' => 4,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '야구공세트',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 20,
                'endurance' => 30,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '접시',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 10,
                'endurance' => 4,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '텔레비전',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 20,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '테이블',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 20,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '선반',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 15,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '보검',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 20,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '빈병',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 1,
                'endurance' => 10,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '빈캔',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 2,
                'endurance' => 10,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '유리잔',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 10,
                'endurance' => 4,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '냄비',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 10,
                'endurance' => 4,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '쇠사슬',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 15,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '후라이팬',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 15,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '소방용도끼',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut]),
                'point' => 20,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '소화기',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 12,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '관음보살상',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 5,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '염라대왕상',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 7,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '아수라상',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 10,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '지장보살상',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 8,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '양궁',
                'attack_type' => IntegerUtil::defactorize([AttackType::Bow, AttackType::Melee]),
                'point' => 20,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 1,
                'ammo_type' => AmmoType::Arrow,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '곡괭이',
                'attack_type' => IntegerUtil::defactorize([AttackType::Stab]),
                'point' => 15,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '스카프',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 10,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '샤벨',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 5,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '암석',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 20,
                'endurance' => 8,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '목탁',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '솔도파',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 4,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '연필',
                'attack_type' => IntegerUtil::defactorize([AttackType::Stab]),
                'point' => 2,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '지우개',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '플라스크',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '대걸레',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 8,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '흰분필',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 2,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '빨간분필',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 2,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '노란분필',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 2,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '파란분필',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 2,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '인체모형',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 3,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '거대삼각자',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 4,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '거대콤파스',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 8,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '의자',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 4,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '대나무',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 6,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '목검',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 12,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '화승총',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 20,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 1,
                'ammo_type' => AmmoType::MusketBall,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '명도마사무네',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 23,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '일본궁',
                'attack_type' => IntegerUtil::defactorize([AttackType::Bow, AttackType::Melee]),
                'point' => 18,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 1,
                'ammo_type' => AmmoType::Arrow,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '전기인두',
                'attack_type' => IntegerUtil::defactorize([AttackType::Stab]),
                'point' => 6,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '고장난노트북',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 10,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '수리검',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 30,
                'endurance' => 15,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '헤비크로스보우',
                'attack_type' => IntegerUtil::defactorize([AttackType::Bow, AttackType::Melee]),
                'point' => 30,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 1,
                'ammo_type' => AmmoType::Arrow,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '면도칼',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut]),
                'point' => 5,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '버터플라이나이프',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 8,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '화투',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '트럼프카드',
                'attack_type' => IntegerUtil::defactorize([AttackType::Throw]),
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '휴대용게임기',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 2,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '비누',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 1,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '칫솔',
                'attack_type' => IntegerUtil::defactorize([AttackType::Melee]),
                'point' => 1,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '요도마사무네',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 25,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => '요도무라마사',
                'attack_type' => IntegerUtil::defactorize([AttackType::Cut, AttackType::Stab]),
                'point' => 23,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Weapon,
                'name' => 'M16A2',
                'attack_type' => IntegerUtil::defactorize([AttackType::Shot, AttackType::Melee]),
                'point' => 30,
                'endurance' => 0,
                'ammo_require' => true,
                'ammo_capacity' => 30,
                'ammo_type' => AmmoType::Rifle556MM,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => '속옷',
                'attack_type' => AttackType::None,
                'point' => 0,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Fabric
            ],
            [
                'type' => ItemType::ArmorHead,
                'name' => '목걸이',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorHead,
                'name' => '머리핀',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 2,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorHead,
                'name' => '안경',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorAccessory,
                'name' => '잡지',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 2,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorAccessory,
                'name' => '다마고치',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 3,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorAccessory,
                'name' => 'CD플레이어',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 3,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorAccessory,
                'name' => '방탄조끼',
                'attack_type' => AttackType::None,
                'point' => 5,
                'endurance' => 10,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorLeg,
                'name' => '등산화',
                'attack_type' => AttackType::None,
                'point' => 3,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorHead,
                'name' => '등산모',
                'attack_type' => AttackType::None,
                'point' => 2,
                'endurance' => 3,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorArm,
                'name' => '팔찌',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 2,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorArm,
                'name' => '털토시',
                'attack_type' => AttackType::None,
                'point' => 2,
                'endurance' => 3,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorArm,
                'name' => '민방위완장',
                'attack_type' => AttackType::None,
                'point' => 2,
                'endurance' => 3,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorArm,
                'name' => '새마을완장',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 2,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorHead,
                'name' => '머리띠',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 3,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => '방화복',
                'attack_type' => AttackType::None,
                'point' => 10,
                'endurance' => 20,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Fabric
            ],
            [
                'type' => ItemType::ArmorHead,
                'name' => '방화헬멧',
                'attack_type' => AttackType::None,
                'point' => 3,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => '승복',
                'attack_type' => AttackType::None,
                'point' => 8,
                'endurance' => 20,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Fabric
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => '신관의옷',
                'attack_type' => AttackType::None,
                'point' => 8,
                'endurance' => 15,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Fabric
            ],
            [
                'type' => ItemType::ArmorLeg,
                'name' => '나막신',
                'attack_type' => AttackType::None,
                'point' => 2,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorHead,
                'name' => '작업용헬멧',
                'attack_type' => AttackType::None,
                'point' => 4,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => '작업복',
                'attack_type' => AttackType::None,
                'point' => 8,
                'endurance' => 10,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Fabric
            ],
            [
                'type' => ItemType::ArmorHead,
                'name' => '오토바이헬멧',
                'attack_type' => AttackType::None,
                'point' => 4,
                'endurance' => 10,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorHead,
                'name' => '리본',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 2,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorLeg,
                'name' => '운동화',
                'attack_type' => AttackType::None,
                'point' => 3,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorArm,
                'name' => '주번완장',
                'attack_type' => AttackType::None,
                'point' => 3,
                'endurance' => 3,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorArm,
                'name' => '토시',
                'attack_type' => AttackType::None,
                'point' => 2,
                'endurance' => 20,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorLeg,
                'name' => '실내화',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 2,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorHead,
                'name' => '녹슨철모',
                'attack_type' => AttackType::None,
                'point' => 4,
                'endurance' => 3,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => '흰옷',
                'attack_type' => AttackType::None,
                'point' => 10,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Fabric
            ],
            [
                'type' => ItemType::ArmorLeg,
                'name' => '장화',
                'attack_type' => AttackType::None,
                'point' => 4,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => '갑주',
                'attack_type' => AttackType::None,
                'point' => 12,
                'endurance' => 20,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Armor
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => '체인메일',
                'attack_type' => AttackType::None,
                'point' => 12,
                'endurance' => 20,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Chain
            ],
            [
                'type' => ItemType::ArmorHead,
                'name' => '투구',
                'attack_type' => AttackType::None,
                'point' => 5,
                'endurance' => 10,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => '가보갑주',
                'attack_type' => AttackType::None,
                'point' => 14,
                'endurance' => 20,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Armor
            ],
            [
                'type' => ItemType::ArmorLeg,
                'name' => '고무신',
                'attack_type' => AttackType::None,
                'point' => 2,
                'endurance' => 4,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorLeg,
                'name' => '하이힐',
                'attack_type' => AttackType::None,
                'point' => 3,
                'endurance' => 3,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorLeg,
                'name' => '군화',
                'attack_type' => AttackType::None,
                'point' => 5,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorHead,
                'name' => '철모',
                'attack_type' => AttackType::None,
                'point' => 5,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorArm,
                'name' => '조교완장',
                'attack_type' => AttackType::None,
                'point' => 5,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorArm,
                'name' => 'MP완장',
                'attack_type' => AttackType::None,
                'point' => 4,
                'endurance' => 5,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => '군복',
                'attack_type' => AttackType::None,
                'point' => 12,
                'endurance' => 40,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Fabric
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => '교복',
                'attack_type' => AttackType::None,
                'point' => 5,
                'endurance' => 30,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Fabric
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => '세라복',
                'attack_type' => AttackType::None,
                'point' => 5,
                'endurance' => 30,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Fabric
            ],
            [
                'type' => ItemType::ArmorBody,
                'name' => '체육복',
                'attack_type' => AttackType::None,
                'point' => 5,
                'endurance' => 30,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::Fabric
            ],
            [
                'type' => ItemType::ArmorLeg,
                'name' => '슬리퍼',
                'attack_type' => AttackType::None,
                'point' => 3,
                'endurance' => 10,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => '와일드세븐',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => '초콜렛',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => '쿠키',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => '고구마',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => '참마',
                'attack_type' => AttackType::None,
                'point' => 20,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => '감자',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => '우엉',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => '당근',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => '양파',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => '마늘',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => '생강',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => '카레가루',
                'attack_type' => AttackType::None,
                'point' => 20,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => '간장',
                'attack_type' => AttackType::None,
                'point' => 20,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => '소스',
                'attack_type' => AttackType::None,
                'point' => 20,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => '영양드링크',
                'attack_type' => AttackType::None,
                'point' => 100,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => '스튜',
                'attack_type' => AttackType::None,
                'point' => 50,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => '빵',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 2,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionStamina,
                'name' => '건빵',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 2,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionHealth,
                'name' => '위스키',
                'attack_type' => AttackType::None,
                'point' => 20,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionHealth,
                'name' => '물',
                'attack_type' => AttackType::None,
                'point' => 20,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionHealth,
                'name' => '약',
                'attack_type' => AttackType::None,
                'point' => 40,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionHealth,
                'name' => '분말쥬스',
                'attack_type' => AttackType::None,
                'point' => 30,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::PotionHealth,
                'name' => '구급약',
                'attack_type' => AttackType::None,
                'point' => 50,
                'endurance' => 3,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Trap,
                'name' => '쥐덫',
                'attack_type' => AttackType::None,
                'point' => 10,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Trap,
                'name' => '지뢰',
                'attack_type' => AttackType::None,
                'point' => 8,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Trap,
                'name' => '피아노선',
                'attack_type' => AttackType::None,
                'point' => 8,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Trap,
                'name' => '강화지뢰',
                'attack_type' => AttackType::None,
                'point' => 20,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Phone,
                'name' => '휴대폰',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => '뇌관',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => '불꽃놀이',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => '헤어스프레이',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => '라이터',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::TempRadar,
                'name' => '간이레이더',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => '샤미센 줄',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Poison,
                'name' => '독약',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Ammo,
                'name' => '탄환 (샷건)',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 24,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::ShotGun12Gauge,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Ammo,
                'name' => '탄환 (9mm)',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 24,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::Pistol9MM,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Ammo,
                'name' => '탄환 (22LR)',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 24,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::Rifle22LR,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Ammo,
                'name' => '탄환 (매그넘)',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 24,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::Magnum357,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Ammo,
                'name' => '탄환 (화승총)',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 24,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::MusketBall,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Ammo,
                'name' => '화살',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 12,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::Arrow,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::ArmorRefine,
                'name' => '바느질도구',
                'attack_type' => AttackType::None,
                'point' => 3,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::WeaponRefine,
                'name' => '숫돌',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => '휘발유',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => '경유',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => '비료',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Speaker,
                'name' => '확성기',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => '배터리',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => '못',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => '도화선',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Radar,
                'name' => '레이더',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => '화약',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => '노트북',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::MobilePc,
                'name' => '모바일PC',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 0,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Item,
                'name' => '창대',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
            [
                'type' => ItemType::Program,
                'name' => '프로그램해제키',
                'attack_type' => AttackType::None,
                'point' => 1,
                'endurance' => 1,
                'ammo_require' => false,
                'ammo_capacity' => 0,
                'ammo_type' => AmmoType::None,
                'armor_material' => ArmorMaterial::None
            ],
        ];

        foreach ($items as $item) {
            DB::table('game_items')->insert($item);
        }
    }
}
