version: '3'

services:
  # Backend 서비스
  backend:
    container_name: express-royale-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html:rw
    environment:
      APP_ENV: local
      APP_DEBUG: true
    command: sh -c "composer install --ignore-platform-reqs --no-interaction --no-plugins --no-scripts && php artisan serve --host=0.0.0.0 --port=8000"

  # Frontend 서비스
  frontend:
    container_name: express-royale-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - NODE_ENV=development
    command: sh -c "npm install --unsafe-perm && npm run dev"

volumes:
  laravel_data: