/**
 * Created by monoless on 2015-12-01.
 */
var itemPlugin = require('../support/itemPlugin');

module.exports = [
    {
        username: '선생님',
        userGender: false,
        userIcon: './static/images/42.jpg',
        message: '',
        messageDying: '',
        messageComment: '',
        ip: '',
        npc: true,
        groupName: '담임',
        attack: 45,
        defence: 49,
        health: 148,
        maxHealth: 148,
        stamina: 300,
        killCount: 0,
        level: 10,
        requireExp: 56,
        place: 0,
        status: 0,
        prevAttacker: '',
        deathAt: null,
        studentNo: 1,
        clubId: null,
        clubName: '정부',
        tactics: 0,
        shotSkill: 100,
        cutSkill: 100,
        throwSkill: 100,
        fistSkill: 100,
        bowSkill: 100,
        meleeSkill: 100,
        bombSkill: 100,
        pokeSkill: 100,
        item5: itemPlugin.empty(),
        item4: itemPlugin.empty(),
        item3: itemPlugin.toObject('weapon11', 1, 17),
        item2: itemPlugin.toObject('heal4', 3, 50),
        item1: itemPlugin.toObject('etc26', 1, 1),
        item0: itemPlugin.toObject('etc39', 1, 1),
        armor: {
            accessory: itemPlugin.empty(),
            foot: itemPlugin.toObject('armor44', 10, 3),
            arm: itemPlugin.empty(),
            body: itemPlugin.toObject('armor43', 30, 5),
            head: itemPlugin.empty()
        },
        weapon: itemPlugin.toObject('weapon14', 150, 23),
        injured: []
    },
    {
        username: '병사1',
        userGender: false,
        userIcon: './static/images/42.jpg',
        message: '',
        messageDying: '',
        messageComment: '',
        ip: '',
        npc: true,
        groupName: '병사',
        attack: 45,
        defence: 43,
        health: 147,
        maxHealth: 147,
        stamina: 300,
        killCount: 0,
        level: 10,
        requireExp: 56,
        place: 1,
        status: 0,
        prevAttacker: '',
        deathAt: null,
        studentNo: 1,
        clubId: null,
        clubName: '정부',
        tactics: 0,
        shotSkill: 100,
        cutSkill: 100,
        throwSkill: 100,
        fistSkill: 100,
        bowSkill: 100,
        meleeSkill: 100,
        bombSkill: 100,
        pokeSkill: 100,
        item5: itemPlugin.empty(),
        item4: itemPlugin.empty(),
        item3: itemPlugin.empty(),
        item2: itemPlugin.toObject('weapon11', 1, 17),
        item1: itemPlugin.toObject('heal1', 2, 20),
        item0: itemPlugin.toObject('stamina18', 2, 20),
        armor: {
            accessory: itemPlugin.empty(),
            foot: itemPlugin.toObject('armor36', 20, 6),
            arm: itemPlugin.empty(),
            body: itemPlugin.toObject('armor40', 20, 6),
            head: itemPlugin.toObject('armor37', 30, 5)
        },
        weapon: itemPlugin.toObject('weapon115', 300, 30),
        injured: []
    }
];