enum ActionType {
    INITIALIZE,
    MESSAGE_RESPONSE,
    MESSAGE_REQUEST,
    UUID_GENERATE,
    UUID_REMOVE,
    REFRESH_RESPONSE,
    REFRESH_REQUEST,
    SIGNIN_RESPONSE,
    SIGNIN_REQUEST,
    SIGNUP_RESPONSE,
    SIGNUP_REQUEST,
}

export default ActionType;
