enum ActionType {
    INITIALIZE,
    UUID_CREATE,
    UUID_REMOVE,
    PAYLOAD_RECYCLE ,
    APPEND_ALERT,
    REMOVE_ALERT,
    SIGNIN_REQUEST,
    SIGNIN_SUCCESS,
    SIGNIN_FAILURE,
    SIGNUP_REQUEST,
    SIGNUP_SUCCESS,
    SIGNUP_FAILURE,
    SIGNOUT,
    ACCOUNT_INFO_REQUEST,
    ACCOUNT_INFO_SUCCESS,
    ACCOUNT_INFO_FAILURE,
}

export default ActionType;
