enum ActionType {
    INITIALIZE,
    UUID_CREATE,
    UUID_REMOVE,
    PAYLOAD_RECYCLE ,
    SIGNIN_REQUEST,
    SIGNIN_SUCCESS,
    SIGNIN_FAILURE,
    SIGNUP_REQUEST,
    SIGNUP_SUCCESS,
    SIGNUP_FAILURE,
    REFRESH_TOKEN_REQUEST,
    REFRESH_TOKEN_SUCCESS,
    REFRESH_TOKEN_FAILURE,
}

export default ActionType;
